# Week 3 Notes: Arrays

 * NumPy
 * array creation
 * array indexing
 * array slicing
 * array broadcasting
 * array masking

## NumPy

```
python_list = [1,2.2, 'oh yeah']
```

NumPy is a Python library used to create and modify arrays

In [1]:
import numpy as np

In [3]:
np.__version__

'1.15.1'

In [4]:
python_list = [10, 20, 30]
numpy_array = np.array(python_list)
numpy_array

array([10, 20, 30])

In [5]:
numpy_array.dtype

dtype('int32')

In [6]:
python_list2 = [0.0, 1.1, 2.2]
numpy_array2 = np.array(python_list2)
numpy_array2

array([0. , 1.1, 2.2])

In [7]:
numpy_array2.dtype

dtype('float64')

In [8]:
python_list3 = [0, 1 ,2.2]
numpy_array3 = np.array(python_list3)
numpy_array3

array([0. , 1. , 2.2])

In [9]:
numpy_array3.dtype

dtype('float64')

In [10]:
python_list4 = [0, 1.1 , 'oh yeah']
numpy_array4 = np.array(python_list4)
numpy_array4

array(['0', '1.1', 'oh yeah'], dtype='<U32')

In [11]:
python_list5 = [0, 1 , 2.2]
numpy_array5 = np.array(python_list5, dtype=np.int32)
numpy_array5

array([0, 1, 2])

In [12]:
numpy_array3.dtype

dtype('int32')

In [14]:
a = np.arange(0,4,1) # start, stop, step
a

array([0, 1, 2, 3])

In [15]:
b = np.arange(-1,2,1)
b

array([-1,  0,  1])

In [16]:
c = np.arange(2,12,2)
c

array([ 2,  4,  6,  8, 10])

In [17]:
d = np.arange(2,12) # default step of 1 is used
d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
f = np.arange(12) # default start of 0 and defaut step of 1 are used
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
g = np.linspace(0,2*np.pi,10)  # start,stop, number of values
g

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [22]:
a = np.arange(0,11,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
a[2]

2

In [24]:
a[5]

5

In [25]:
a[0:4]

array([0, 1, 2, 3])

In [26]:
a[0:8:2]

array([0, 2, 4, 6])

In [28]:
a[:8:2]  # defaut start

array([0, 2, 4, 6])

In [29]:
b = np.array([[0,1,2],[10,20,30]])
b

array([[ 0,  1,  2],
       [10, 20, 30]])

In [30]:
b.shape

(2, 3)

In [31]:
b[1]

array([10, 20, 30])

In [32]:
b[0]

array([0, 1, 2])

In [33]:
# pull out the value 2
# value 2 is in row 0, col 2


In [34]:
b[0,2]

2

In [35]:
# pull out the value 10
# value 10 is in row 1, col 0
b[1,0]

10

In [36]:
b

array([[ 0,  1,  2],
       [10, 20, 30]])

In [37]:
# pull out the column that has 1 and 20
# row 0 and row 1, col 1
b[0:2,1]

array([ 1, 20])

In [38]:
b[:2,1]  #default start is used

array([ 1, 20])

In [39]:
b[:,1]

array([ 1, 20])

In [41]:
b

array([[ 0,  1,  2],
       [10, 20, 30]])

In [44]:
# pull out 20 and 30 from the array
# row 1, col 1 and col 2
b[1,1:3]
b[1,1:]

array([20, 30])

In [45]:
# array broadcasting
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [48]:
b_list = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
b_list*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [49]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
a**2 + 2*a - 3

array([ -3,   0,   5,  12,  21,  32,  45,  60,  77,  96, 117])

In [51]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [52]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [53]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [54]:
np.log10(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        ])

In [55]:
c = np.arange(0,70,10)
c

array([ 0, 10, 20, 30, 40, 50, 60])

In [56]:
# pull out 10, 40, 50
mask =[False, True, False, False, True, True, False]
c[mask]

array([10, 40, 50])

In [57]:
mask = [1,4,5]
c[mask]

array([10, 40, 50])

In [58]:
mask1 = c>20
mask1

array([False, False, False,  True,  True,  True,  True])

In [59]:
c[mask1]

array([30, 40, 50, 60])

In [62]:
# the locations of the elements in the array which are greater than 20
locs = np.where(c>20)

In [63]:
# find the values at the locations in the array which are greater than 20
c[locs]

array([30, 40, 50, 60])

In [65]:
#find the location of the value 50 in the array c
loc = np.where(c==50)
loc

(array([5], dtype=int64),)

In [66]:
# pull out the value at the location
c[loc]

array([50])